In [1]:
import numpy as np
import pandas as pd

In [64]:
import pandas as pd
data=pd.read_csv('studentdata.csv')
x = data.iloc[:, 0].values
y = data.iloc[:, 1].values
from sklearn.preprocessing import MinMaxScaler
minmax_x = MinMaxScaler()
minmax_y = MinMaxScaler()
x = minmax_x.fit_transform(x.reshape(-1, 1))
y = minmax_y.fit_transform(y.reshape(-1,1))
y

array([[0.        ],
       [0.55046277],
       [0.4581728 ],
       [0.59158031],
       [0.82447704],
       [0.69054749],
       [0.71178837],
       [0.40782129],
       [0.64777815],
       [0.58793112],
       [0.34833881],
       [0.75391323],
       [0.44995446],
       [0.64869327],
       [0.73843081],
       [0.43086868],
       [0.76005564],
       [0.97517956],
       [0.25451478],
       [0.37375348],
       [0.7746977 ],
       [0.99316651],
       [0.37931603],
       [0.29229952],
       [0.64851183],
       [0.63937837],
       [0.94659747],
       [0.94324623],
       [0.70303387],
       [0.7680677 ],
       [0.4699987 ],
       [0.14412302],
       [0.66687549],
       [0.96611674],
       [0.62925972],
       [0.51795151],
       [0.68396883],
       [0.28231866],
       [0.45167172],
       [0.43215526],
       [0.31147318],
       [0.39888714],
       [0.76025577],
       [0.44127945],
       [0.9434658 ],
       [0.20586093],
       [0.33227775],
       [0.835

In [65]:
import pandas as pd
data=pd.read_csv('studentdata.csv')
x = data.iloc[:, 0].values
y = data.iloc[:, 1].values
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
x = sc_x.fit_transform(x.reshape(-1, 1))
y = sc_y.fit_transform(y.reshape(-1,1))
y

array([[-2.66651176],
       [-0.21538463],
       [-0.62633786],
       [-0.03229448],
       [ 1.00475931],
       [ 0.40839133],
       [ 0.50297376],
       [-0.85054551],
       [ 0.21794595],
       [-0.04854375],
       [-1.11541194],
       [ 0.69054936],
       [-0.66293287],
       [ 0.22202084],
       [ 0.62160848],
       [-0.74791896],
       [ 0.71790058],
       [ 1.67581471],
       [-1.5331961 ],
       [-1.00224427],
       [ 0.78309945],
       [ 1.75590787],
       [-0.9774751 ],
       [-1.3649464 ],
       [ 0.22121292],
       [ 0.180543  ],
       [ 1.54854301],
       [ 1.53362047],
       [ 0.46399128],
       [ 0.75357708],
       [-0.57367894],
       [-2.02475385],
       [ 0.3029835 ],
       [ 1.63545934],
       [ 0.13548623],
       [-0.36015233],
       [ 0.37909756],
       [-1.40938966],
       [-0.65528619],
       [-0.74219   ],
       [-1.27956897],
       [-0.89032789],
       [ 0.71879173],
       [-0.70156137],
       [ 1.53459818],
       [-1

In [66]:
import pandas as pd
data=pd.read_csv('studentdata.csv')
x = data.iloc[:, 0].values
y = data.iloc[:, 1].values
from sklearn.preprocessing import MaxAbsScaler
mas_x = MaxAbsScaler()
mas_y = MaxAbsScaler()
x = mas_x.fit_transform(x.reshape(-1, 1))
y = mas_y.fit_transform(y.reshape(-1,1))
y

array([[0.32010654],
       [0.69436258],
       [0.63161523],
       [0.72231812],
       [0.88066309],
       [0.78960526],
       [0.8040468 ],
       [0.59738157],
       [0.76052667],
       [0.71983707],
       [0.55693982],
       [0.83268721],
       [0.62602764],
       [0.76114885],
       [0.82216082],
       [0.61305134],
       [0.8368634 ],
       [0.98312474],
       [0.49314948],
       [0.57421909],
       [0.84681844],
       [0.99535395],
       [0.57800103],
       [0.51883907],
       [0.76102549],
       [0.75481571],
       [0.96369197],
       [0.96141349],
       [0.79809467],
       [0.84231075],
       [0.63965558],
       [0.41809484],
       [0.77351082],
       [0.97696299],
       [0.74793611],
       [0.67225839],
       [0.78513247],
       [0.51205315],
       [0.62719519],
       [0.61392608],
       [0.53187512],
       [0.5913073 ],
       [0.83699947],
       [0.62012955],
       [0.96156277],
       [0.46007004],
       [0.54602001],
       [0.888

In [63]:
import pandas as pd
data=pd.read_csv('studentdata.csv')
x = data.iloc[:, 0].values
y = data.iloc[:, 1].values
from sklearn.preprocessing import robust_scale
rb_x = robust_scale(x)
rb_y = robust_scale(y)
rb_y

array([-1.80467508, -0.15169316, -0.42883026, -0.02822151,  0.67114293,
        0.26896653,  0.33275068, -0.58003057,  0.14053469, -0.03917964,
       -0.7586502 ,  0.45924721, -0.45350906,  0.1432827 ,  0.41275512,
       -0.51082167,  0.47769222,  1.12368676, -1.04039391, -0.68233261,
        0.52166079,  1.17769968, -0.66562887, -0.92693031,  0.14273786,
        0.11531103,  1.03785775,  1.02779434,  0.30646182,  0.5017516 ,
       -0.39331833, -1.37188879,  0.197882  ,  1.09647206,  0.08492582,
       -0.24932106,  0.24921151, -0.95690179, -0.44835232, -0.50695819,
       -0.8693538 , -0.60685886,  0.47829319, -0.47955921,  1.02845369,
       -1.1864963 , -0.80687987,  0.70518872, -0.86745823,  0.95407585,
        0.35612938, -0.31560127, -0.29506352, -0.30761182,  0.05596505,
       -0.04636542,  0.30871021,  0.63946671,  0.56019259, -0.57167612,
       -0.46799575, -0.10398137,  0.62063865, -0.58282414, -0.10165923,
       -1.21807048,  0.59387462,  1.04149781, -0.08595224, -0.86

In [60]:
import pandas as pd
data=pd.read_csv('studentdata.csv')
x = data.iloc[:, 0].values
y = data.iloc[:, 1].values
from sklearn.preprocessing import quantile_transform
qt_x = quantile_transform(data,n_quantiles=20)
qt_x

C:\Users\gautam.y.kumar\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\data.py:2553: FutureWarning: The default value of `copy` will change from False to True in 0.23 in order to make it more consistent with the default `copy` values of other functions in :mod:`sklearn.preprocessing.data` and prevent unexpected side effects by modifying the value of `X` inplace. To avoid inplace modifications of `X`, it is recommended to explicitly set `copy=True`
  FutureWarning)


array([[0.04802407, 0.        ],
       [0.66198903, 0.40982766],
       [0.90262018, 0.30792182],
       [0.43953954, 0.47933858],
       [0.86969689, 0.844858  ],
       [0.71111175, 0.61774187],
       [0.62177982, 0.65809092],
       [0.17764059, 0.2138409 ],
       [0.45494062, 0.56743899],
       [0.63415854, 0.47404931],
       [0.38045694, 0.1508632 ],
       [0.69016546, 0.72855612],
       [0.31551632, 0.28714501],
       [0.8266911 , 0.56902105],
       [0.76225903, 0.70829603],
       [0.47737882, 0.24865874],
       [0.34712567, 0.736594  ],
       [0.87981586, 0.97509151],
       [0.38666661, 0.05165108],
       [0.16475103, 0.17807578],
       [0.96272618, 0.75846787],
       [0.95578696, 0.99314227],
       [0.43967581, 0.18373899],
       [0.25532153, 0.08552592],
       [0.60779861, 0.56870738],
       [0.86045022, 0.55291748],
       [0.78638791, 0.94517881],
       [0.93428288, 0.93751111],
       [0.42148065, 0.63115561],
       [0.55120099, 0.74854716],
       [0.

In [58]:
import pandas as pd
data=pd.read_csv('studentdata.csv')
x = data.iloc[:, 0].values
y = data.iloc[:, 1].values
from sklearn.preprocessing import power_transform
pt_x = power_transform(data)
pt_x

C:\Users\gautam.y.kumar\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\data.py:3009: FutureWarning: The default value of 'method' will change from 'box-cox' to 'yeo-johnson' in version 0.23. Set the 'method' argument explicitly to silence this warning in the meantime.
  FutureWarning)


array([[-1.70760714, -2.53776988],
       [ 0.46475777, -0.23478319],
       [ 1.29212789, -0.64109007],
       [-0.14726129, -0.05161408],
       [ 1.11734119,  1.00867212],
       [ 0.64044677,  0.39437112],
       [ 0.3401281 ,  0.49099501],
       [-0.99520777, -0.85979907],
       [-0.08234057,  0.2007713 ],
       [ 0.37483689, -0.06792208],
       [-0.35965826, -1.11530507],
       [ 0.55951687,  0.68352854],
       [-0.48964461, -0.6769347 ],
       [ 0.94966392,  0.2049001 ],
       [ 0.80251405,  0.61262646],
       [ 0.00534661, -0.75995831],
       [-0.43546456,  0.71170211],
       [ 1.16664697,  1.71350208],
       [-0.33908544, -1.51158048],
       [-1.0455628 , -1.00652661],
       [ 1.76506694,  0.77896187],
       [ 1.68666073,  1.79852993],
       [-0.14668666, -0.98263982],
       [-0.75824823, -1.35302555],
       [ 0.30249154,  0.20408145],
       [ 1.07226641,  0.16290156],
       [ 0.86204094,  1.57877587],
       [ 1.50401508,  1.56301071],
       [-0.22344656,

In [57]:
import pandas as pd
data=pd.read_csv('studentdata.csv')
x = data.iloc[:, 0].values
y = data.iloc[:, 1].values
from sklearn.preprocessing import Normalizer
Nor_x = Normalizer().fit_transform(data)
Nor_x

array([[0.71581056, 0.69829452],
       [0.61346201, 0.78972424],
       [0.70120184, 0.71296282],
       [0.55290806, 0.83324227],
       [0.56551367, 0.82473892],
       [0.57622319, 0.81729238],
       [0.54826555, 0.8363043 ],
       [0.55325601, 0.83301128],
       [0.53820452, 0.84281427],
       [0.59329068, 0.80498831],
       [0.63561696, 0.77200459],
       [0.55024685, 0.83500204],
       [0.58012398, 0.81452819],
       [0.61085781, 0.79174032],
       [0.57158004, 0.82054632],
       [0.6276378 , 0.77850549],
       [0.47453419, 0.88023707],
       [0.52644635, 0.85020835],
       [0.68254185, 0.73084651],
       [0.56370257, 0.82597785],
       [0.61947071, 0.78501977],
       [0.55287666, 0.83326311],
       [0.63836845, 0.76973094],
       [0.62894964, 0.77744604],
       [0.5666846 , 0.82393481],
       [0.62187038, 0.78312019],
       [0.5147399 , 0.85734639],
       [0.55548169, 0.83152877],
       [0.50892973, 0.86080807],
       [0.51824075, 0.85523478],
       [0.